# we replace default elasticsearch.yml with only the options we care about
# see elasticsearch doc for configuration options

network.host: {{ internal_ip }}
http.port: {{ elastic_port }}
path.data: /var/db/elasticsearch
path.logs: /var/log/elasticsearch
