---
- name: install/update oauth2_proxy
  shell: 'export GOROOT=/usr/local/go GOPATH=/usr/local; go get github.com/bitly/oauth2_proxy'
  args:
    executable: /usr/local/bin/bash
  environment: "{{ proxy_env }}"

- name: configure elasticsearch
  template:
    src: elasticsearch.yml
    dest: "{{ elastic_configuration }}"
  notify: restart elasticsearch

- name: configure logstash
  template:
    src: logstash_{{logstash_variant}}.conf
    dest: "{{ logstash_configuration }}"
  notify: restart logstash

- name: configure kibana
  template:
    src: kibana.yml
    dest: "{{ kibana_configuration }}"
  notify: restart kibana

- name: configure oauth2_proxy
  template:
    src: oauth2_proxy.conf
    dest: "{{ oauth2_proxy_configuration }}"
    mode: 0660
    owner: "{{ worker_account }}"
    group: "wheel"
  notify: restart supervisor

- name: remove
  shell: 'rm -rf "{{ logstash_tmp_dir }}"'

- name: enable elk
  lineinfile:
    dest: "/etc/rc.conf"
    line: "{{item.option}}=\"{{item.value}}\""
    regexp: "^{{item.option}}=.*"
    state: present
  notify: restart logstash
  with_items:
  - option: "elasticsearch_enable"
    value: "YES"
  - option: "logstash_enable"
    value: "YES"
  - option: "logstash_log"
    value: "YES"
  - option: "logstash_log_file"
    value: "/var/log/logstash.log"
  # workaround logstash6 apparent incompatibility with FreeBSD. Note that the directory needs to be
  # removed before each startup. Unfortunately this does not work, but apparently logstash ignores
  # the JAVA_OPTS environment variable set by the service startup file and requires LS_JAVA_OPTS.
  # So the service startup script was modified by hand to force
  # LS_JAVA_OPTS=-Djava.io.tmpdir=/tmp/logstashdir
  - option: "logstash_java_opts"
    value: "-Djava.io.tmpdir={{ logstash_tmp_dir }}"
  - option: "kibana_enable"
    value: "YES"


- name: start elasticsearch
  service:
    name: elasticsearch
    enabled: true
    state: started

- name: start logstash
  service:
    name: logstash
    enabled: true
    state: started

- name: start kibana
  service:
    name: kibana
    enabled: true
    state: started
