- name: install mandatory packages
  package:
    name: "{{ mandatory_packages[ansible_distribution] }}"
    state: present
  environment: "{{ proxy_env }}"

- name: install utility packages
  package:
    name: "{{ utility_packages[ansible_distribution] }}"
    state: present
  environment: "{{ proxy_env }}"
